name: Test and Deploy
run-name: Test and Deploy
on: [push]
jobs:
  pre-deploy-checks:
    env:
      DEPLOY_ENV: dev
      REGION: ${{ variables.DEV_REGION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: pip install -r ./cdk-app/requirements-dev.txt
      - name: Run Tests
        run: |
        pytest .
        echo $REGION
        working-directory: ./cdk-app/

  deploy-to-dev:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: dev
      ACCOUNT: ${{ variables.AWS_ACCESS_KEY }}
      REGION: ${{ variables.DEV_REGION }}
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: pip install -r ./cdk-app/requirements-dev.txt
      # - name: Run CDK Synth
      #   run: cdk synth
      #   working-directory: ./cdk-app/

  deploy-to-staging:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: staging
      ACCOUNT: 700433791282
      REGION: ${{ variables.STAGING_REGION }}
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: pip install -r ./cdk-app/requirements-dev.txt
      # - name: Run CDK Synth
      #   run: cdk synth
      #   working-directory: ./cdk-app/

  deploy-to-prod:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: prod
      ACCOUNT: 700433791282
      REGION: ${{ variables.PROD_REGION }}
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: pip install -r ./cdk-app/requirements-dev.txt
      # - name: Run CDK Synth
      #   run: cdk synth
      #   working-directory: ./cdk-app/