name: Test and Deploy
run-name: Test and Deploy
on: [push]
jobs:
  pre-deploy-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: pip install -r ./cdk-app/requirements-dev.txt
      - name: Run Tests
        run: pytest .
        working-directory: ./cdk-app/